### ISSUE TITLE
.travis.yml: The 'sudo' tag is now deprecated in Travis CI

### ISSUE THREAD

**Issue by cclauss** [nodejs/llparse-test-fixture#1]
[Travis are now recommending removing the __sudo__ tag](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).

"_If you currently specify __sudo: false__ in your __.travis.yml__, we recommend removing that configuration_"

**Comment by Trott** [comment]
As best as I can tell, Travis is not enabled for this repo. @indutny Do you want me to enable it or would you prefer to remove `.travis.yml`? (Or am I mistaken and it's totally running for this repo?)

**Comment by Trott** [comment]
Oh, it's enabled/running. The badge in the README needs to be updated (`s/indutny/nodejs/`). That's all.

**Comment by indutny** [comment]
I don't mind changes to either!

**Comment by fanatid** [comment]
Can be closed... (travis not used now).

**Comment by Trott** [comment]
.travis.yml file was removed in https://github.com/nodejs/llparse-test-fixture/commit/13534ac1a98646f20459bbc3e8fcdcbb9a8edd72
